import { Octokit } from '@octokit/rest';

/**
 * Initialize Octokit with the user's stored OAuth token, user agent, and hard timeout
 */
export function getOctokit(token) {
  if (!token) {
    throw new Error('GITHUB_NOT_CONNECTED: No GitHub token found. Please connect your GitHub account in the menu.');
  }
  return new Octokit({
    auth: token,
    userAgent: 'Atlas-AI-Agent/1.0',
    request: { timeout: 8000 }, // 8-second hard timeout prevents infinite loading
  });
}

/**
 * 1. List the user's repositories
 */
export async function listUserRepos(token) {
  const octokit = getOctokit(token);
  const { data } = await octokit.rest.repos.listForAuthenticatedUser({
    sort: 'updated',
    per_page: 10,
    visibility: 'all',
  });

  return data.map((r) => ({
    name: r.name,
    full_name: r.full_name,
    private: r.private,
    description: r.description || 'No description',
    url: r.html_url,
    stars: r.stargazers_count,
    language: r.language,
  }));
}

/**
 * 2. Create a new repository
 */
export async function createRepo(token, { repoName, isPrivate = false, description = '' }) {
  const octokit = getOctokit(token);
  const { data } = await octokit.rest.repos.createForAuthenticatedUser({
    name: repoName,
    description: description || 'Created by Atlas AI',
    private: isPrivate,
    auto_init: true,
  });
  return { success: true, url: data.html_url, fullName: data.full_name };
}

/**
 * 3. Commit and push a single file directly to a branch
 */
export async function commitFile(token, { owner, repo, path, content, commitMessage, branch = 'main' }) {
  const octokit = getOctokit(token);

  // Check if file already exists to get its SHA for update
  let sha;
  try {
    const existing = await octokit.rest.repos.getContent({ owner, repo, path, ref: branch });
    sha = existing.data.sha;
  } catch {
    sha = undefined; // New file creation
  }

  const { data } = await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path,
    message: commitMessage || `Update ${path} via Atlas AI`,
    content: Buffer.from(content).toString('base64'),
    branch,
    sha,
  });

  return { success: true, commitUrl: data.commit.html_url };
}

/**
 * 4. Create a Pull Request
 */
export async function createPullRequest(token, { owner, repo, title, headBranch, baseBranch = 'main', body }) {
  const octokit = getOctokit(token);
  const { data } = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    head: headBranch,
    base: baseBranch,
    body: body || 'Automated PR generated by Atlas AI',
  });
  return { success: true, prUrl: data.html_url, prNumber: data.number };
}
